[build]
  base = "/"
  command = "npm run build:js"
  publish = "/public/js/bundle"
  [build.environment]
    NODE_VERSION = "20"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/app/:splat"
